# Generated by Django 5.2.7 on 2025-10-28 09:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, unique=True)),
                ("acronym", models.CharField(blank=True, max_length=30, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("wpi_number", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(default="UNDEFINED", max_length=40)),
                ("un_locode", models.CharField(blank=True, max_length=10, null=True)),
                ("world_water_body", models.TextField(blank=True, null=True)),
                ("tidal_range_m", models.FloatField(blank=True, null=True)),
                ("entrance_width_m", models.FloatField(blank=True, null=True)),
                ("anchorage_depth_m", models.FloatField(blank=True, null=True)),
                ("oil_terminal_depth_m", models.FloatField(blank=True, null=True)),
                ("maximum_vessel_length_m", models.FloatField(blank=True, null=True)),
                ("maximum_vessel_draft_m", models.FloatField(blank=True, null=True)),
                (
                    "supplies_potable_water",
                    models.BooleanField(default=False, null=True),
                ),
                ("supplies_fuel_oil", models.BooleanField(default=False, null=True)),
                (
                    "dry_dock",
                    models.CharField(
                        choices=[
                            ("SMALL", "SMALL"),
                            ("MEDIUM", "MEDIUM"),
                            ("LARGE", "LARGE"),
                        ],
                        default="MEDIUM",
                        max_length=15,
                        null=True,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(blank=True, max_length=5)),
                ("name", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=20, unique=True)),
                ("description", models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShipClass",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25, unique=True)),
                ("transit_speed_kn", models.FloatField(blank=True)),
                ("draught_m", models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("acronym", models.CharField(max_length=10, unique=True)),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("imo", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.TextField(blank=True, null=True, unique=True)),
                ("acronym", models.CharField(blank=True, max_length=20, null=True)),
                ("main_lay", models.BooleanField(default=False, null=True)),
                (
                    "dynamic_positioning",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("year_built", models.IntegerField(blank=True, null=True)),
                ("length_overall_m", models.FloatField(blank=True, null=True)),
                ("width_m", models.FloatField(blank=True, null=True)),
                ("draught_m", models.FloatField(blank=True, null=True)),
                ("gross_tonnage_t", models.FloatField(blank=True, null=True)),
                ("deadweight_t", models.FloatField(blank=True, null=True)),
                ("max_speed_kn", models.FloatField(blank=True, null=True)),
                ("transit_speed_kn", models.FloatField(blank=True, null=True)),
                ("fuel_capacity_t", models.FloatField(blank=True, null=True)),
                ("fuel_safety_level_t", models.FloatField(blank=True, null=True)),
                (
                    "port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vessel.port",
                    ),
                ),
                (
                    "ship_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vessel.shipclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalParameter",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timewindow_h", models.IntegerField(blank=True, null=True)),
                ("max_wind_speed_kn", models.FloatField(blank=True, null=True)),
                ("max_wave_m", models.FloatField(blank=True, null=True)),
                ("max_current_kn", models.FloatField(blank=True, null=True)),
                ("standard_consumption", models.IntegerField(blank=True, null=True)),
                ("theoretical_speed_kn", models.IntegerField(blank=True, null=True)),
                ("applicable_speed_kn", models.IntegerField(blank=True, null=True)),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vessel.purpose",
                    ),
                ),
                (
                    "ship_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="operational_parameters",
                        to="vessel.shipclass",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="vessel.task"
                    ),
                ),
            ],
            options={
                "unique_together": {("ship_class_id", "purpose_id", "task_id")},
            },
        ),
        migrations.CreateModel(
            name="VesselFlagMmsiHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("flag_start_date", models.DateField(null=True)),
                (
                    "flag_end_date",
                    models.DateField(default=datetime.date.today, null=True),
                ),
                ("mmsi", models.IntegerField(blank=True, null=True)),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vessel.vessel",
                    ),
                ),
            ],
            options={
                "unique_together": {("mmsi", "vessel_id", "flag_start_date")},
            },
        ),
        migrations.CreateModel(
            name="VesselProjectHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vessel.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="vessel.task"
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vessel.vessel",
                    ),
                ),
            ],
            options={
                "unique_together": {("project_id", "vessel_id", "task_id")},
            },
        ),
        migrations.CreateModel(
            name="VesselPurpose",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("primary_purpose", models.BooleanField(blank=True)),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vessel.purpose"
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vessel.vessel"
                    ),
                ),
            ],
            options={
                "unique_together": {("vessel_id", "purpose_id")},
            },
        ),
        migrations.CreateModel(
            name="VesselQualification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vessel.task"
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vessel.vessel"
                    ),
                ),
            ],
            options={
                "unique_together": {("vessel_id", "task_id")},
            },
        ),
        migrations.CreateModel(
            name="VesselStakeholder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vessel.organisation",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vessel.role"
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vessel.vessel"
                    ),
                ),
            ],
            options={
                "unique_together": {("organisation_id", "role_id", "vessel_id")},
            },
        ),
    ]
